### PR TITLE
Fix AmplitudeEnvelope Recipe

### PR DESCRIPTION
**Pull request by emurray2**
The `ADSRView` wasn't doing anything because the `env` inside conductor needs to receive a `MIDIEvent` in order for it to trigger.

### CODE REVIEW

**Comment by aure** [comment]
Hmm, seems to me we should bring the noteOn/Off stuff into start/stop instead of putting it here into the Cookbook.

**Comment by emurray2** [comment]
> Hmm, seems to me we should bring the noteOn/Off stuff into start/stop instead of putting it here into the Cookbook.

I agree. It would be nice to have one place to keep all of this code so we don't need to change all the cookbook oscillators. Start/Stop also seems more intuitive.

The only thing I noticed with that is the `start()` and `stop()` functions are part of the `Node` extension, and they bypass each effect. If the adsr is bypassed during a release (which happens when the noteOff signal is sent), then the release will always be instant.

Maybe since this noteOn/noteOff functionality seems more specific to the ADSR, I could add a functions in the `AmplitudeEnvelope.swift` that are called `startTrigger()` and `stopTrigger()`?

I'll close this for now and think about it some more.

**Comment by aure** [comment]
Isn't `openGate` and `closeGate` calling `trigger` and `detrigger` internally for this purpose?

**Comment by emurray2** [comment]
That's right. I didn't realize there was a `Gated` node type. Those functions would be useful.

**Pull request closed without merging**
