### PR TITLE
Added unversioned TeamID infrastructure.

### PR DESCRIPTION
**Pull request by JanX2**
This is described in detail in the file "Shared.xcconfig".

### CODE REVIEW

**Comment by aure** [comment]
This change breaks our Github CI checks

**Comment by JanX2** [comment]
Yes. I don’t see a way around it. You need to add the TeamID you are building for to CI.

**Comment by JanX2** [comment]
This should allow CI to build the project.

**Comment by JanX2** [comment]
And this merge seems to break CI again.

**Comment by aure** [comment]
Closing since this breaks CI

**Comment by aure** [comment]
It didn't pass and then got woefullly out of date. If you can make another PR, that would be great!  Thanks in advance.

**Pull request closed without merging**
